sudo: required

language: rust

rust:
  - nightly
  - stable

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

services:
  - redis-server
  - memcached

matrix:
  allow_failures:
    - rust: stable
  fast_finish: true

cache:
  - cargo
  - apt: true

script:
  - cargo test --verbose --all
  # - cargo bench --verbose --all

after_success: |
    wget https://github.com/shaneutt/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
    ls target/debug &&
    ./kcov-master/tmp/usr/local/bin/kcov –coveralls-id=$TRAVIS_JOB_ID –exclude-pattern=/.cargo target/kcov target/debug/riak-*
