sudo: required

language: rust

rust:
  - nightly
  - stable

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

services:
  - redis-server
  - memcached
  - docker

matrix:
  allow_failures:
    - rust: stable
  fast_finish: true

# cache:
#   - cargo
#   - apt: true

jobs:
  include:
    - stage: initial
      script: docker run -e "IP=0.0.0.0" -d -p 7000-7007:7000-7007 grokzen/redis-cluster:4.0.9

    - stage: unittest
      script: cargo test --verbose --all

stages:
  - initial
  - unittest